# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: Kanzat/jwiki
        path: 'jwiki'
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build JWiki with Gradle
      uses: gradle/gradle-build-action@v2.2.1
      with:
        build-root-directory: jwiki
        arguments: publishToMavenLocal
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: SSH-SCP-SSH to ToolForge
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: login.toolforge.org
        user: Kanzat
        key: ${{ secrets.DC_PASS }}
        connect_timeout: 10s
        first_ssh: |
          become kanzattool1
          toolforge-jobs delete mycronjob
          rm wikipedia-need-attention-pages4-1.0-SNAPSHOT-jar-with-dependencies.jar
        scp: |
          './target/*-with-dependencies.jar' => /data/project/kanzattool1/
        last_ssh: |
          echo '/usr/bin/java -jar /data/project/kanzattool1/wikipedia-need-attention-pages4-1.0-SNAPSHOT-jar-with-dependencies.jar "/data/project/kanzattool1/credentials.properties"' > startcmd.sh
          toolforge-jobs run mycronjob --command ./startcmd.sh --image jdk17 --email all --schedule "0 4 * * *"
